Repository Arquisoft/lomap_en3a, pull requests merged in 2023-04, with the labels that each got.

#73 Fix section 8
  docs/images/Domain Model.jpg
Labels: documentation

#82 Server database
  restapi/api.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/server.ts
  restapi/src/controllers/checks.ts
  restapi/src/controllers/places/PlacesController.ts
  restapi/src/models/Place.ts
  restapi/src/types/PlaceType.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/pages/Home.tsx
  webapp/src/types/PlaceType.ts
Labels: Feature, High level requirements

#86 Store and retrieve data from PODs
  webapp/package-lock.json
  webapp/package.json
  webapp/src/adapters/map/LeafletMapAdapter.tsx
  webapp/src/adapters/solid/Assembler.ts
  webapp/src/adapters/solid/PODManager.ts
  webapp/src/adapters/solid/PlaceManager.ts
  webapp/src/domain/Map.tsx
  webapp/src/domain/Place.tsx
  webapp/src/domain/Placemark.tsx
  webapp/src/pages/AddPlace.tsx
  webapp/src/pages/Home.tsx
Labels: Feature

#87 Tests ivan
  restapi/src/controllers/checks.ts
  restapi/src/controllers/places/PlacesController.ts
  restapi/tests/api.test.ts
  webapp/src/api/api.ts
Labels: testing

#89 Change acl of a resource
  webapp/src/adapters/solid/PODManager.ts
  webapp/src/pages/Home.tsx
Labels: Feature

#91 Map filter
  .github/workflows/lomap_en3a.yml
  package-lock.json
  package.json
  webapp/.dockerignore
  webapp/Dockerfile
  webapp/src/App.css
  webapp/src/adapters/map/LeafletMapAdapter.tsx
  webapp/src/components/ListUsers.tsx
  webapp/src/components/MapFilter.tsx
  webapp/src/components/tests/MapFilter.test.tsx
  webapp/src/domain/User.ts
  webapp/src/pages/Home.tsx
  webapp/src/styles/mapFilter.css
Labels: Feature, High level requirements

#90 Places information overview page and review page
  webapp/package-lock.json
  webapp/package.json
  webapp/src/adapters/solid/Assembler.ts
  webapp/src/adapters/solid/PlaceManager.ts
  webapp/src/components/place/IPlacePage.tsx
  webapp/src/components/place/OverviewPage.tsx
  webapp/src/components/place/ReviewsPage.test.tsx
  webapp/src/components/place/ReviewsPage.tsx
  webapp/src/domain/Place.tsx
  webapp/src/domain/Place/PlaceComment.tsx
  webapp/src/domain/Place/PlacePhotos.tsx
  webapp/src/domain/Place/PlaceRating.tsx
  webapp/src/pages/AddPlace.tsx
  webapp/src/pages/Home.tsx
  webapp/src/pages/PointInformation.tsx
  webapp/src/styles/AddPlace.css
  webapp/src/styles/OverviewPage.css
  webapp/src/styles/pointInfo.css
Labels: High level requirements

#93 Tests for UI header (navigation menu and logout)
  webapp/package.json
  webapp/src/App.test.tsx
  webapp/src/components/MapFilter.tsx
  webapp/src/components/tests/Header.test.tsx
  webapp/src/components/tests/LogoutButton.test.tsx
  webapp/src/components/tests/NavMenu.test.tsx
Labels: testing

#94 Map filter
  webapp/src/adapters/map/LeafletMapAdapter.tsx
  webapp/src/components/MapFilter.tsx
  webapp/src/components/tests/MapFilter.test.tsx
  webapp/src/domain/Place/PlaceCategory.tsx
  webapp/src/styles/mapFilter.css
Labels: Feature, High level requirements

#97 Documentation update points 08, 09, 12
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  docs/12_glossary.adoc
Labels: documentation

#96 Places information
  webapp/package.json
  webapp/src/components/place/ReviewsPage.test.tsx
  webapp/src/components/tests/PlaceInformation.test.tsx
  webapp/src/domain/Map.tsx
  webapp/src/domain/Place.tsx
Labels: Feature, High level requirements

#102 Store comments
  webapp/src/adapters/map/LeafletMapAdapter.tsx
  webapp/src/adapters/solid/Assembler.ts
  webapp/src/adapters/solid/PODManager.ts
  webapp/src/components/place/IPlacePage.tsx
  webapp/src/components/place/OverviewPage.tsx
  webapp/src/components/place/ReviewsPage.tsx
  webapp/src/domain/Place/PlaceComment.tsx
  webapp/src/domain/Placemark.tsx
  webapp/src/pages/AddPlace.tsx
  webapp/src/pages/PointInformation.tsx
Labels: Feature

#107 Store reviews
  webapp/src/adapters/solid/Assembler.ts
  webapp/src/adapters/solid/PODManager.ts
  webapp/src/components/place/OverviewPage.tsx
  webapp/src/components/place/ReviewsPage.tsx
  webapp/src/domain/Place/PlaceRating.tsx
  webapp/src/pages/Home.tsx
Labels: Feature

#100 Deployment diagram
  docs/07_deployment_view.adoc
  docs/images/Deployment View.svg
  docs/images/deployment_view.jpg
Labels: documentation

#101 Update of section 5 with business model
  docs/05_building_block_view.adoc
  docs/images/businessmodel/Business model Level 1.svg
  docs/images/businessmodel/Business model Level 2.svg
  docs/images/businessmodel/Business model Level 3.svg
Labels: documentation

#92 Section 8 update
  docs/08_concepts.adoc
  docs/images/Domain Model.jpg
  restapi/package-lock.json
  webapp/src/adapters/solid/FriendManager.ts
  webapp/src/adapters/solid/SolidSessionManager.tsx
Labels: documentation

#116 Section 6 of the documentation
  docs/06_runtime_view.adoc
Labels: documentation

#122 119 share places with friends
  docs/06_runtime_view.adoc
  webapp/src/domain/Placemark.tsx
  webapp/src/pages/AddPlace.tsx
  webapp/src/pages/PointInformation.tsx
Labels: High level requirements

#123 UI enhancements: Friends Places and Maps
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.css
  webapp/src/adapters/map/LeafletMapAdapter.tsx
  webapp/src/components/ImageList.tsx
  webapp/src/components/ListUsers.tsx
  webapp/src/components/MapFilter.tsx
  webapp/src/components/NavElement.tsx
  webapp/src/components/UserMenu.tsx
  webapp/src/components/basic/PaginatedTable.tsx
  webapp/src/components/friends/ListUsers.tsx
  webapp/src/components/friends/UserPage.tsx
  webapp/src/components/friends/UserPlaceHolder.tsx
  webapp/src/components/place/ReviewsPage.tsx
  webapp/src/pages/Friends.tsx
  webapp/src/pages/Home.tsx
  webapp/src/pages/Login.tsx
  webapp/src/pages/PointInformation.tsx
  webapp/src/styles/friendsPage.css
  webapp/src/styles/header.css
  webapp/src/styles/layout.css
  webapp/src/styles/login.css
  webapp/src/styles/mapFilter.css
  webapp/src/styles/navmenu.css
  webapp/src/styles/userProfile.css
Labels: enhancement, Feature, High level requirements

#124 Database refinement and SonarCloud fix (restapi coverage enabled)
  .github/workflows/lomap_en3a.yml
  restapi/jest.config.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/server.ts
  restapi/settings.ts
  restapi/src/controllers/places/PlacesController.ts
Labels: enhancement

#125 Deployment with https
  .github/workflows/lomap_en3a.yml
  docker-compose-deploy.yml
  webapp/.env
  webapp/Dockerfile
  webapp/package-lock.json
  webapp/package.json
  webapp/server.js
Labels: bug, Feature

#132 Add groups of users
  webapp/src/adapters/solid/Assembler.ts
  webapp/src/adapters/solid/FriendManager.ts
  webapp/src/adapters/solid/PODManager.ts
  webapp/src/adapters/solid/SolidSessionManager.ts
  webapp/src/domain/Group.ts
  webapp/src/domain/Map.ts
  webapp/src/domain/Place.ts
  webapp/src/domain/Place/PlaceCategory.ts
  webapp/src/domain/Place/PlaceComment.ts
  webapp/src/domain/Place/PlacePhotos.ts
  webapp/src/domain/Place/PlaceRating.ts
  webapp/src/domain/Placemark.ts
  webapp/src/pages/Home.tsx
Labels: Feature

#129 128 improvement of the readme file
  README.md
  README_es.md
  docs/images/LoMap_logo.PNG
  docs/images/LoMap_logo.ico
  restapi/README.md
  restapi/README_es.md
  webapp/README.md
Labels: documentation

#136 UI enhancement + Groups Logic
  docs/09_design_decisions.adoc
  webapp/package-lock.json
  webapp/package.json
  webapp/public/map-magnifier.png
  webapp/src/App.css
  webapp/src/App.tsx
  webapp/src/adapters/map/LeafletMapAdapter.test.tsx
  webapp/src/adapters/map/LeafletMapAdapter.tsx
  webapp/src/adapters/solid/PODManager.ts
  webapp/src/components/MapFilter.tsx
  webapp/src/components/NavMenu.tsx
  webapp/src/components/UserMenu.tsx
  webapp/src/components/basic/ImageList.tsx
  webapp/src/components/basic/LoadingPage.tsx
  webapp/src/components/basic/PaginatedTable.tsx
  webapp/src/components/basic/PassmeDropdown.tsx
  webapp/src/components/basic/ReactTable.tsx
  webapp/src/components/friends/UserPage.tsx
  webapp/src/components/place/ReviewsPage.tsx
  webapp/src/components/social/AddGroup.tsx
  webapp/src/components/social/EmptyFriendsList.tsx
  webapp/src/components/social/GroupInfo.tsx
  webapp/src/components/social/ListGroups.tsx
  webapp/src/components/social/ListUsers.tsx
  webapp/src/components/social/UserPage.tsx
  webapp/src/components/social/UserPlaceHolder.tsx
  webapp/src/components/tests/MapFilter.test.tsx
  webapp/src/pages/Home.tsx
  webapp/src/pages/MapInfo.tsx
  webapp/src/pages/PointInformation.tsx
  webapp/src/pages/Social.tsx
  webapp/src/pages/UserStuff.tsx
  webapp/src/styles/friendsPage.css
  webapp/src/styles/header.css
  webapp/src/styles/mapFilter.css
  webapp/src/styles/mapInfo.css
  webapp/src/styles/navmenu.css
  webapp/src/styles/paginatedTablesContentStyle.css
  webapp/src/styles/userProfile.css
  webapp/src/tests/components/Header.test.tsx
  webapp/src/tests/components/LogoutButton.test.tsx
  webapp/src/tests/components/MapFilter.test.tsx
  webapp/src/tests/components/NavMenu.test.tsx
  webapp/src/tests/components/NewPlacePopup.test.tsx
  webapp/src/tests/components/UserMenu.test.tsx
  webapp/src/tests/components/basic/ImageList.test.tsx
  webapp/src/tests/components/basic/PassmeDropdown.test.tsx
  webapp/src/tests/components/basic/ReactTable.test.tsx
  webapp/src/tests/components/social/ListUsers.test.tsx
  webapp/src/tests/components/social/UserPlaceHolder.test.tsx
  webapp/src/tests/pages/PlaceInformation.test.tsx
  webapp/src/tests/pages/Social.test.tsx
Labels: bug, enhancement, Feature, High level requirements, testing

#134 Privacy enhancement develop merge
  webapp/.env
  webapp/src/adapters/map/LeafletMapAdapter.tsx
  webapp/src/components/place/AddPlace.tsx
  webapp/src/components/place/OverviewPage.tsx
  webapp/src/components/place/PrivacyComponent.tsx
  webapp/src/pages/MapInfo.tsx
  webapp/src/pages/PointInformation.tsx
  webapp/src/pages/Social.tsx
  webapp/src/pages/UserStuff.tsx
  webapp/src/styles/AddPlace.css
  webapp/src/styles/OverviewPage.css
  webapp/src/styles/PrivacyComponent.css
  webapp/src/styles/mapInfo.css
  webapp/src/styles/pointInfo.css
  webapp/src/tests/components/AddPlace.test.tsx
  webapp/src/tests/components/MapInfo.test.tsx
  webapp/src/tests/components/Overview.test.tsx
  webapp/src/tests/components/PrivacyComponent.test.tsx
  webapp/src/tests/pages/Social.test.tsx
Labels: High level requirements

#133 131 business logic friends page
  webapp/src/adapters/solid/FriendManager.ts
  webapp/src/adapters/solid/PODManager.ts
  webapp/src/adapters/solid/PlaceManager.ts
  webapp/src/domain/User.ts
Labels: Feature
