Repository Arquisoft/lomap_en3a, pull requests merged in 2023-05, with the labels that each got.

#144 Share with groups of friends
  webapp/src/components/map/AddMap.tsx
  webapp/src/components/social/GroupInfo.tsx
  webapp/src/domain/Map.ts
  webapp/src/styles/AddMap.css
Labels: Finish

#145 Privacy places and maps logic integration
  webapp/src/components/place/AddPlace.tsx
  webapp/src/pages/MapInfo.tsx
  webapp/src/pages/PointInformation.tsx
  webapp/src/styles/mapInfo.css
Labels: Finish

#148 Refactor PODManager
  webapp/src/adapters/solid/PODManager.ts
  webapp/src/adapters/solid/repositories/AbstractSolidRepository.ts
  webapp/src/adapters/solid/repositories/GroupsRepository.ts
  webapp/src/adapters/solid/repositories/InteractionsRepository.ts
  webapp/src/adapters/solid/repositories/MapsRepository.ts
  webapp/src/adapters/solid/repositories/PlacesRepository.ts
Labels: Finish

#147 Simplify view of maps and places
  webapp/src/components/place/AddPlace.tsx
  webapp/src/components/place/OverviewPage.tsx
  webapp/src/pages/MapInfo.tsx
  webapp/src/pages/PointInformation.tsx
  webapp/src/styles/mapInfo.css
Labels: Finish

#155 AddGroup, ListGroup, MapFilter unit tests
  sonar-project.properties
  webapp/src/components/social/AddGroup.tsx
  webapp/src/components/social/ListGroups.tsx
  webapp/src/tests/components/AddGroup.test.tsx
  webapp/src/tests/components/ListGroups.test.tsx
  webapp/src/tests/components/MapFilter.test.tsx
Labels: testing

#150 131-business-logic-friends-page BUG
  webapp/src/adapters/solid/FriendManager.ts
  webapp/src/domain/User.ts
Labels: bug

#149 Integrating the logic of reviews and comment
  webapp/src/components/place/IPlacePage.tsx
  webapp/src/components/place/OverviewPage.tsx
  webapp/src/pages/PointInformation.tsx
  webapp/src/tests/components/AddPlace.test.tsx
  webapp/src/tests/components/Overview.test.tsx
Labels: Finish

#153 UI enhancement - See friends Maps and Points
  webapp/package-lock.json
  webapp/package.json
  webapp/public/background_login.jpg
  webapp/public/globe.png
  webapp/public/marker_black.png
  webapp/src/adapters/map/LeafletMapAdapter.tsx
  webapp/src/components/Footer.tsx
  webapp/src/components/Layout.tsx
  webapp/src/components/UserMenu.tsx
  webapp/src/components/basic/EmptyList.tsx
  webapp/src/components/basic/LoadingPage.tsx
  webapp/src/components/social/AddGroup.tsx
  webapp/src/components/social/EmptyFriendsList.tsx
  webapp/src/components/social/GroupInfo.tsx
  webapp/src/components/social/ListGroups.tsx
  webapp/src/components/social/ListUsers.tsx
  webapp/src/components/social/UserPage.tsx
  webapp/src/components/social/UserPlaceHolder.tsx
  webapp/src/pages/Home.tsx
  webapp/src/pages/Login.tsx
  webapp/src/pages/MapInfo.tsx
  webapp/src/pages/PointInformation.tsx
  webapp/src/pages/Social.tsx
  webapp/src/pages/UserStuff.tsx
  webapp/src/styles/layout.css
  webapp/src/styles/login.css
  webapp/src/styles/social.css
  webapp/src/styles/userProfile.css
  webapp/src/tests/components/UserMenu.test.tsx
  webapp/src/tests/pages/Social.test.tsx
  webapp/src/tests/pages/UserStuff.test.tsx
Labels: enhancement, Feature, testing, Finish

#156 Coverage uo283428
  sonar-project.properties
  webapp/src/components/place/AddPlace.tsx
  webapp/src/tests/components/AddPlace.test.tsx
  webapp/src/tests/components/PrivacyComponent.test.tsx
  webapp/src/tests/components/social/GroupInfo.test.tsx
  webapp/src/tests/components/social/UserPage.test.tsx
Labels: testing, Finish

#151 Images of a place in the popup
  webapp/src/components/basic/ImageList.tsx
  webapp/src/domain/Place.ts
  webapp/src/pages/PointInformation.tsx
Labels: Feature, Finish

#159 UI fixes - Bugs on the PointInformation and several other
  webapp/src/adapters/solid/repositories/GroupsRepository.ts
  webapp/src/components/basic/ImageList.tsx
  webapp/src/components/place/OverviewPage.tsx
  webapp/src/components/place/PrivacyComponent.tsx
  webapp/src/components/social/AddGroup.tsx
  webapp/src/components/social/ListGroups.tsx
  webapp/src/components/social/UserPage.tsx
  webapp/src/components/social/UserPlaceHolder.tsx
  webapp/src/domain/User.ts
  webapp/src/pages/Login.tsx
  webapp/src/pages/PointInformation.tsx
  webapp/src/pages/Social.tsx
  webapp/src/pages/UserStuff.tsx
  webapp/src/styles/login.css
  webapp/src/styles/pointInfo.css
  webapp/src/styles/social.css
Labels: bug, Finish

#160 Initialize folder permissions on login
  webapp/src/adapters/solid/PODManager.ts
  webapp/src/adapters/solid/repositories/GroupsRepository.ts
  webapp/src/pages/Login.tsx
  webapp/src/pages/MapView.tsx
Labels: Feature, Finish

#162 UI fixes carlos
  webapp/src/App.css
  webapp/src/components/map/AddMap.tsx
  webapp/src/components/place/ReviewsPage.tsx
  webapp/src/components/social/GroupInfo.tsx
  webapp/src/components/social/UserPlaceHolder.tsx
  webapp/src/pages/MapView.tsx
  webapp/src/pages/PublicMapView.tsx
Labels: Finish

#163 UI fixes guille - Small fixes and unit tests
  webapp/src/adapters/map/LeafletMapAdapter.test.tsx
  webapp/src/components/basic/BackButton.tsx
  webapp/src/components/place/OverviewPage.tsx
  webapp/src/components/place/PrivacyComponent.tsx
  webapp/src/components/social/FriendsList.tsx
  webapp/src/components/social/GroupInfo.tsx
  webapp/src/components/social/UserPage.tsx
  webapp/src/components/social/UserPlaceHolder.tsx
  webapp/src/pages/MapInfo.tsx
  webapp/src/pages/UserStuff.tsx
  webapp/src/styles/userProfile.css
  webapp/src/tests/components/basic/BackButton.test.tsx
  webapp/src/tests/components/place/OverviewPage.test.tsx
  webapp/src/tests/components/social/FriendsList.test.tsx
  webapp/src/tests/pages/UserStuff.test.tsx
Labels: testing, Finish

#164 Tests for the map adapters
  sonar-project.properties
  webapp/src/adapters/map/LeafletMapAdapter.test.tsx
  webapp/src/adapters/map/LeafletMapAdapter.tsx
  webapp/src/adapters/map/LeafletPublicMapAdapter.tsx
  webapp/src/components/place/PrivacyComponent.tsx
  webapp/src/tests/components/maps/LeafletMapAdapter.test.tsx
  webapp/src/tests/components/maps/LeafletPublicMapAdapter.test.tsx
Labels: testing

#170 Tests
  webapp/src/components/social/UserPage.tsx
  webapp/src/tests/components/Overview.test.tsx
  webapp/src/tests/components/maps/LeafletMapAdapter.test.tsx
Labels: testing

#169 New version of the Building Block View.
  docs/05_building_block_view.adoc
  docs/images/05_Building_Block_Level_1.PNG
  docs/images/05_Building_Block_Level_1_2.jpg
Labels: documentation

#175 Friend place bug
  webapp/src/adapters/solid/repositories/GroupsRepository.ts
  webapp/src/adapters/solid/repositories/MapsRepository.ts
  webapp/src/adapters/solid/repositories/PlacesRepository.ts
  webapp/src/components/social/UserPage.tsx
Labels: bug

#168 e2e tests + unit tests fixes
  .github/workflows/lomap_en3a.yml
  webapp/e2e/features/filter.feature
  webapp/e2e/steps/add-place.steps.ts
  webapp/e2e/steps/filter.steps.ts
  webapp/package.json
  webapp/src/tests/components/maps/LeafletMapAdapter.test.tsx
Labels: testing

#166 RestApi-update: webId & category on public places
  restapi/src/controllers/checks.ts
  restapi/src/controllers/places/PlacesController.ts
  restapi/src/models/Place.ts
  restapi/src/models/Placemark.ts
  restapi/src/types/PlaceType.ts
  webapp/src/adapters/map/LeafletPublicMapAdapter.tsx
  webapp/src/adapters/solid/PODManager.ts
  webapp/src/adapters/solid/repositories/PlacesRepository.ts
  webapp/src/api/api.ts
  webapp/src/components/place/AddPlace.tsx
  webapp/src/domain/place/PlaceCategory.ts
  webapp/src/pages/PointInformation.tsx
  webapp/src/pages/PublicMapView.tsx
  webapp/src/types/PlaceType.ts
Labels: Finish

#176 Update for the documentation of the solid adapters.
  docs/05_building_block_view.adoc
  docs/images/05_Building_Block_Level_1_1.jpg
  docs/images/05_Building_Block_Level_1_1_1.jpg
Labels: documentation

#177 Solved deployment with restapi
  .github/workflows/lomap_en3a.yml
  docker-compose-deploy.yml
  restapi/Dockerfile
  restapi/api.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/server.ts
  restapi/src/controllers/places/PlacesController.ts
  webapp/Dockerfile
Labels: bug

#174 Update
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
Labels: Finish

#178 RestApi-test
  restapi/src/models/Placemark.ts
  restapi/tests/api.test.ts
Labels: testing, Finish
