Repository Arquisoft/lomap_en3a, pull requests merged in 2023-03, with the labels that each got.

#40 Login page
  docs/05_building_block_view.adoc
  docs/10_quality_scenarios.adoc
  webapp/package-lock.json
  webapp/package.json
  webapp/public/favicon.ico
  webapp/public/logo192.png
  webapp/public/logo512.png
  webapp/src/App.css
  webapp/src/App.tsx
  webapp/src/adapters/solid/SolidSessionManager.tsx
  webapp/src/index.tsx
  webapp/src/pages/Home.tsx
  webapp/src/pages/Login.tsx
  webapp/src/styles/fonts/PatrickHand-Regular.ttf
  webapp/src/styles/login.css
Labels: Feature, Prototype

#43 Updated section 4
  docs/04_solution_strategy.adoc
Labels: documentation

#45 Update for sections 3.1 and 5.
  docs/05_building_block_view.adoc
  docs/images/05_Building_Block_Level_1.PNG
  docs/images/05_Building_Block_Overall_View.PNG
  docs/images/BusinessContext.jpg
Labels: documentation

#47 Map component
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/adapters/map/LeafletMapAdapter.tsx
  webapp/src/assets/map/new_marker.png
  webapp/src/components/NewPlacePopup.tsx
  webapp/src/domain/Map.tsx
  webapp/src/domain/Placemark.tsx
  webapp/src/pages/Home.tsx
Labels: Feature, Prototype

#53 Maintain session after page refresh
  webapp/src/adapters/solid/SolidSessionManager.tsx
Labels: Feature, Prototype

#54 Place form
  docs/01_introduction_and_goals.adoc
  webapp/src/App.tsx
  webapp/src/adapters/map/LeafletMapAdapter.tsx
  webapp/src/domain/MapPoint.tsx
  webapp/src/pages/AddPlace.tsx
  webapp/src/styles/AddPlace.css
Labels: documentation, Feature, Prototype

#56 Add technical debt
  docs/11_technical_risks.adoc
Labels: documentation

#57 Show place form
  webapp/src/App.tsx
  webapp/src/adapters/map/LeafletMapAdapter.tsx
  webapp/src/pages/AddPlace.tsx
Labels: Feature, Prototype

#58 46 adding friends functionality
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/adapters/solid/FriendManager.ts
  webapp/src/adapters/solid/SolidSessionManager.tsx
  webapp/src/components/ListUsers.tsx
  webapp/src/domain/User.ts
  webapp/src/pages/Friends.tsx
Labels: Feature, Prototype

#59 52 busines logic for adding a new pin in the pods user
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/adapters/solid/PlaceManager.ts
  webapp/src/adapters/solid/SolidSessionManager.tsx
  webapp/src/domain/Place.tsx
  webapp/src/domain/Placemark.tsx
  webapp/src/domain/User.ts
  webapp/src/pages/AddPlace.tsx
Labels: Feature, Prototype

#61 Point information
  webapp/package-lock.json
  webapp/package.json
  webapp/src/adapters/solid/PlaceManager.ts
  webapp/src/components/ImageList.tsx
  webapp/src/domain/Place.tsx
  webapp/src/pages/PointInformation.tsx
  webapp/src/styles/pointInfo.css
Labels: Feature, Prototype

#67 Fix places not being added on page reload
  webapp/src/adapters/solid/SolidSessionManager.tsx
  webapp/src/components/Layout.tsx
Labels: bug, Prototype

#69 Point information logic
  package-lock.json
  package.json
  webapp/src/adapters/map/LeafletMapAdapter.tsx
  webapp/src/pages/PointInformation.tsx
Labels: bug, Feature, Prototype
